### ISSUE TITLE
.pth file discrepency

### ISSUE THREAD

**Issue by madwards28** [MarkisKelly22/draw-and-guess#21]
@David-Mc The .pth file specified in dng.py:
**load_model(net, path='ml/models/2018-04-10 09:16:59.032209.pth')**

is different than the file linked in the readme:
**2018-04-10 00:08:16.607028.pth**

**Comment by David-Mc** [comment]
Attempted fix: [a55924d](https://github.com/MarkisKelly22/draw-and-guess/commit/a55924d3ae382e4c099b074921d5827c6b488075)
